# Log configuration
log:
  # Log level
  level: info
  # Log format
  format: text

# Server configurations
# server:
#   listenAddr: ""
#   port: 8080

# Internal Server configurations
# internalServer:
#   listenAddr: ""
#   port: 9090

# Cachet configuration
cachet:
  url: http://localhost
  apiKey: API_KEY

# Targets
targets:
  - component:
      name: COMPONENT_NAME
      # groupName: GROUP_NAME
      status: PARTIAL_OUTAGE
    alerts:
      - name: SERVICE_OFFLINE
    #   - labels:
    #       label1: value1
    # incident:
    #   name: ""
    #   content: ""
    #   status: INVESTIGATING
    #   public: true

