// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/oxyno-zeta/prometheus-cachethq/pkg/prometheus-cachethq/metrics (interfaces: Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// IncrementComponentManagedCounter mocks base method.
func (m *MockClient) IncrementComponentManagedCounter(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementComponentManagedCounter", arg0)
}

// IncrementComponentManagedCounter indicates an expected call of IncrementComponentManagedCounter.
func (mr *MockClientMockRecorder) IncrementComponentManagedCounter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementComponentManagedCounter", reflect.TypeOf((*MockClient)(nil).IncrementComponentManagedCounter), arg0)
}

// IncrementIncidentManagedCounter mocks base method.
func (m *MockClient) IncrementIncidentManagedCounter(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncrementIncidentManagedCounter", arg0, arg1)
}

// IncrementIncidentManagedCounter indicates an expected call of IncrementIncidentManagedCounter.
func (mr *MockClientMockRecorder) IncrementIncidentManagedCounter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementIncidentManagedCounter", reflect.TypeOf((*MockClient)(nil).IncrementIncidentManagedCounter), arg0, arg1)
}

// Instrument mocks base method.
func (m *MockClient) Instrument(arg0 string) gin.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instrument", arg0)
	ret0, _ := ret[0].(gin.HandlerFunc)
	return ret0
}

// Instrument indicates an expected call of Instrument.
func (mr *MockClientMockRecorder) Instrument(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instrument", reflect.TypeOf((*MockClient)(nil).Instrument), arg0)
}

// PrometheusHTTPHandler mocks base method.
func (m *MockClient) PrometheusHTTPHandler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrometheusHTTPHandler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// PrometheusHTTPHandler indicates an expected call of PrometheusHTTPHandler.
func (mr *MockClientMockRecorder) PrometheusHTTPHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrometheusHTTPHandler", reflect.TypeOf((*MockClient)(nil).PrometheusHTTPHandler))
}
